### ISSUE TITLE
Add info about how to obtain API token

### ISSUE THREAD

**Issue by mortenscheel** [danielboendergaard/nummerplade-api#1]
Hi Kameli,

You should probably add information about how to obtain an API token in the readme.

**Comment by danielboendergaard** [comment]
Hi Morten

We are working on a new website which will clear things up :)

At the moment you need to contact us to obtain an API token. You can find our contact information on http://www.nummerpladeapi.dk/ It is a paid service, but we provide demo tokens if you want to try it out.
