### ISSUE TITLE
How to tell vehicle types from each other?

### ISSUE THREAD

**Issue by mortenscheel** [danielboendergaard/nummerplade-api#2]
So far we're happy with the API, but it's hard to find any official documentation about what kinds of values DMR contains.

Here's a few concrete examples that puzzle me:
- Can I tell a normal motorcycle from a "veteran" motorcycle, (except maybe by using the first registration year as a hint)
- How do you tell an ATV from a normal car? Only difference I can spot is that ATV's generally have smaller engine sizes.
- Scooters vs mopeds (knallert 30)?

I know you're not responsible for the data, I just can't find any answers anywhere else. Would it be possible to provide an overview of which categories there are, and how to tell them apart?

Thanks,
Morten

**Comment by danielboendergaard** [comment]
Hi Morten

Please send these questions to info@kameli.dk

Thanks :)
