### ISSUE TITLE
Er alle køretøjer up to date?

### ISSUE THREAD

**Issue by mortenscheel** [danielboendergaard/nummerplade-api#3]
Hej igen, vi kan vist lige så godt skrive på dansk :)

Jeg er ved at omskrive nogle systemer til at bruge denne API, og faldt over noget mystisk da jeg lavede stikprøver.

Data om nummerpladen AT67516 indeholder hverken motorstørrelse, topfart eller typegodkendelses-nummer. Men når jeg slår den op på f.eks. biltorvet, så findes alle oplysningerne.

Er der en forklaring på det?

Mvh,
Morten

**Comment by danielboendergaard** [comment]
Hej Morten

Vores data kommer fra det Digitale Motorregister og vi har derfor kun det der er angivet fra deres side. Så vidt jeg ved har biltorvet deres data fra en anden kilde, men skriv gerne en mail til info@kameli.dk for et mere uddybende svar. Min kollega René har mere styr på datakilder osv. så jeg er sikker på han kan hjælpe :)
